# api/endpoints.py

from fastapi import APIRouter, Query
from typing import List
from api.models import Record
import pandas as pd
from src.config import PROCESSED_DATA_DIR
import glob

router = APIRouter()

@router.get("/data/sample", response_model=List[Record])
def get_sample_data(limit: int = Query(10, ge=1, le=100)):
    """
    Return sample records from the processed data.
    """
    # Find the CSV generated by Spark
    files = glob.glob(str(PROCESSED_DATA_DIR) + "/part-*.csv")
    if not files:
        raise FileNotFoundError("No processed data found. Run the ETL pipeline first.")

    df = pd.read_csv(files[0])
    return df.head(limit).to_dict(orient="records")
